---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Create EC2
    ec2_instance:
      key_name: sydney
      image_id: "ami-07620139298af599e"
      instance_type: t2.micro
      region: "ap-southeast-2"
      vpc_subnet_id: "10.0.0.0/16"
      wait: true
      volumes:
        - device_name: /dev/xvda
          ebs:
            volume_type: gp2
            volume_size: 20
            delete_on_termination: true
            encrypted: true
      name: Ngomo
      tags:
        created_by: JILL
        Owner: regina
        App_Name: albert
        Cost_Center: Cost Center
        Business_Unit: Business_unit
      user_data: |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        service httpd start
        chkconfig httpd on
        echo "<html><body><h1>Hello JJTech Team</h1></body></html>" > /var/www/html/index.html

#  - debug:
#      msg: ec2_instance
#  - debug:
#      msg: "{{ ec2.results[0].instance_ids }}"
